export const Colors = {
  WHITE: "#FFFFFF",
  DARK_ORANGE: "#fc5b1b",
  LIGHT_ORANGE: "#ef632b",
  BRIGHT_ORANGE: "#ff682b",
  YELLOW_ORANGE: "#fec430",
  BRIGHT_GREEN: "#96bd13",
  PALE_GREEN: "#889d02",
  GREEN_WHITE: "#fdffcb",
  DARK_GREY: "#363c51",
  LIGHT_GREY: "#53535e",
  LIGHT_YELLOW: "#fff9d9",
  LIGHT_BLUE: "#d1ecf8",
  LIGHT_PEACH: "#fee4dd",
};
